# Generated by Django 3.0.6 on 2020-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='Latitud del lugar'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='longitude',
            field=models.IntegerField(default=0, verbose_name='Longitud del lugar'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='terrainType',
            field=models.TextField(default='', verbose_name='Tipo de terreno'),
        ),
    ]
